### ISSUE TITLE
Firefox: Can't import or drag keyfile for 'import account'

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#49]
When importing an account from the dashboard and selecting 'import via keyfile', both options (either by dragging or clicking to import the file) are not possible on Firefox because the browser extension closes and resets back to the dashboard.

**Comment by fyang1024** [comment]
This looks a Firefox bug. I tested Import Json on Metamask in Firefox, it has the same issue.
The issue were reported 3 years ago but hasn’t been fixed.
https://discourse.mozilla.org/t/how-to-load-file-into-webextension-popup/10134/3
https://bugzilla.mozilla.org/show_bug.cgi?id=1292701
