### ISSUE TITLE
Create Account via Dashboard allows user to click back to change password, resulting in strange behaviour

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#50]
User is able to click back and change passwords, which leads to weird bugs: one of which involved the mnemonic confirmation not registering. Also, its not clear to the user what password is required to decrypt the keyfile (At the moment, its the very first one used to login) - especially if they click back thinking they can change it. 

Possible solution: A new restrictive screen for creating account via dashboard that only allows for account name + mnemonic.

Foreseeable issue: Once we implement parachain selection in step 3, user will be forced to this screen when creating an account via dashboard.

**Comment by ttaoS** [comment]
the issue is resolved. the create password step will be only enable if there is no account created.

**Comment by anjj123** [comment]
I think this works for now. Later create account should have its own screen and ill create a related issue for us to look at when we get time
