### ISSUE TITLE
General Dashboard UX Enhancements #1

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#52]
Dashboard UX Enhancements list: 

1. Dashboard should display the custom name of the account and not "My Polkadot Wallet"
2. Dashboard should display the newly created account and not go back to the previous account
3. Can't see or copy full public key anymore (suggestion: make the account icon clickable to copy address, and have a '+' icon appear when mouse hovers over it)
4. Closing and opening extension or logging in/out defaults back to the first account in the dropdown list - it should be the last selected account

**Comment by ttaoS** [comment]
@anjj123 I have done some improvements for this issue. Could you please verify it when you have time? You can close it if all items have been addressed.
