### ISSUE TITLE
Dashboard UI Enhancements #1

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#55]
List of Dashboard UI Enhancements:

1. Firefox: Dropdown selection sits under Account Name (also, we need to enforce character limits for Account Names so that it doesn't flow past the screen or push the drop down below the name)

![Screen Shot 2019-05-06 at 3 56 08 pm](https://user-images.githubusercontent.com/39804936/57223471-8783dc00-7049-11e9-89a2-12939d69d932.png)

2. Contents need to sit closer together (Account name + address) + Balance Box needs to sit a bit higher (per the designs) to make room for more transaction information below 

Design: 
![Screen Shot 2019-05-06 at 4 01 09 pm](https://user-images.githubusercontent.com/39804936/57223530-bd28c500-7049-11e9-8ca0-9bebb4000831.png)

3. White line to separate top toolbar from the body of the dashboard, see below as reference:

![Screen Shot 2019-05-06 at 10 03 48 pm](https://user-images.githubusercontent.com/39804936/57223810-ac2c8380-704a-11e9-86b5-9169b27e285a.png)

**Comment by fyang1024** [comment]
All the 3 changes have been done. @anjj123 please test and close it if they look ok
