### ISSUE TITLE
Bottom Toolbar UI Enhancements #1

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#56]
List of bottom toolbar UI enhancements: 

1. Have selected option stay highlighted; 

2. Can we have icon colors reflect color theme chosen by user (or a universal lighter color closer to designs)

**Comment by fyang1024** [comment]
<img width="373" alt="Screen Shot 2019-06-18 at 11 52 01 pm" src="https://user-images.githubusercontent.com/20808865/59690103-2a706e00-9224-11e9-8655-95d8e04d9585.png">
