### ISSUE TITLE
Chrome: Minimising Browser and Accessing Extension Anomalous Behaviour

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#63]
When minimising the chrome browser and opening the extension, it sometimes freezes and when clicking on buttons/dropdowns opens a new window/tab in chrome. Minimising makes it easier to drag n drop files for import account, so this may be commonly experienced.

**Comment by ttaoS** [comment]
Could you please provide steps to reproduce it or screenshots?

**Comment by anjj123** [comment]
I haven't been able to recreate this since. I'm not sure what changed, so I'll close it for now
