### ISSUE TITLE
Import ed25519 account json file not working

### ISSUE THREAD

**Issue by fyang1024** [SpeckleOS/speckle-browser-extension#64]
When user tries to import an ed25519 account by keystore file, it reports error

**Comment by anjj123** [comment]
Also had an issue where an account disappeared after attempting to do so. I'll see if I can repeat the issue.

**Comment by fyang1024** [comment]
It turns out that 5FzwuR7AKDuMFyzvRDb4GtALSirgsAn5R4dmQio76Wfn9akc.json address checksum is incorrect, but Polkadot app chooses to ignore the checksum. Their code snippet has a comment about that.
```
 // FIXME Just for the transition period (ignoreChecksum)
        publicKey: this.decodeAddress(json.address, true)
```
I just changed our code to ignore checksum as well. I believe it should be removed at some stage.

**Comment by anjj123** [comment]
Cool, im going to leave this as on hold so we can revisit later and update accordingly

**Comment by anjj123** [comment]
> 
> 
> Also had an issue where an account disappeared after attempting to do so. I'll see if I can repeat the issue.

I haven't been able to recreate this. Let's keep an eye on it.

**Comment by anjj123** [comment]
@fyang1024 do we need to keep note that we need to consider checksum later when they implement it? we should keep an issue on-hold so we don't forget later

**Comment by fyang1024** [comment]
> @fyang1024 do we need to keep note that we need to consider checksum later when they implement it? we should keep an issue on-hold so we don't forget later

I'll add a FIXME or TODO at that piece of code just like polkadot-ui
