### ISSUE TITLE
Sending transaction to one account, updates the balance for other accounts 

### ISSUE THREAD

**Issue by anjj123** [SpeckleOS/speckle-browser-extension#67]
When the balance of one account is updated (e.g. someone sends DOTs to it), it changes the currently selected accounts balance to the recipient account. 

**Steps to reproduce**

1. Select an account in the wallet; 
2. Send dots to another account in the wallet (that account must have a minimum of 103 dots to be recognised in the nodedb);
3. Balance will update for the currently selected account

**See gif of reproduced steps**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/39804936/57578352-e88a3480-74cd-11e9-85a1-3370de06875c.gif)

**Comment by fyang1024** [comment]
It should be fixed now. updateBalance is pure function now which accepts address as parameter instead of reading from component props, so that it should keep address and balance result in sync

**Comment by anjj123** [comment]
Issue is still live for me

**Comment by fyang1024** [comment]
@anjj123 put a temp fix now by removing balance subscription. The downside is until you switch account you cannot see updated balance if any. But it's better to show outdated balance than other account's balance, I guess.

**Comment by anjj123** [comment]
For records: a new fix was put in and balance unsubscription was patched in.

**Comment by anjj123** [comment]
@fyang1024 gif above, you can see I had to click on "imported account" twice to switch for example
