### ISSUE TITLE
Onboarding experience feedback

### ISSUE THREAD

**Issue by Tbaut** [SpeckleOS/speckle-browser-extension#78]
As promised, here is the issue recap of my on-boarding experience and the little quirks or remarks I have. 

First of all it looks nice, great job ! 
When testing I usually put myself in the situation of a real use case, as if I was on mainnet. I wanted to do things well and when creating my account I decided to store the seed in a password manager. So when the extension is giving me a seed, I copy/paste it on my local password manager. That's actually what the UI is asking me to do (pasting it somewhere secure). Now the next step asks for a verification of that seed..  right so I have to pop up my account manager to check the seed. But at this point the extension looses focus and goes back to the account creation with password. Entering the same strong password gives a new seed.. hence I have no other way than actually writing down this seed phrase whenever it's given to me, pasting it anywhere will never work because the extension will loose focus.

Writing down the seed on a piece of paper is actually what crypto wallets usually recommend, but I'd tend to go the other way: not talking about the seed too much (other than for validators it shouldn't be needed, it's too insecure to "paste it somewhere", and because you create a `sr25519` account by default validators aren't your target, so the seed isn't a big deal).

Another approach which I like, is to not bother users with the backup unless they have significant amount of funds say 50$. Don't bother users at account creation, on board them quickly and then teach them slowly, it's a matter of timing.

I did notice after messing up with the UI that I was able to copy/paste the seed in the verification field. But that's not a suitable and safe solution as many users will not paste it anywhere else and potentially lose it.

**Comment by EdwardAThomson** [comment]
Yep! I'd still like to see this flow updated. :-)

Doing another round of testing and when I lose focus on the extension (e.g. to save my seed phrase), it takes me back to the start. In the current test it didn't generate a new account at least.

**Comment by anjj123** [comment]
This is being worked on in another issue! Thanks for the feedback :)
