### ISSUE TITLE
Generate QR code for receiving address

### ISSUE THREAD

**Issue by fyang1024** [SpeckleOS/speckle-browser-extension#87]
It'll be handy for a mobile wallet with QR code scanning function to transfer funds to the address in the extension.

**Comment by hskang9** [comment]
I think we would need receive button or get it by clicking identicon on dashboard.

**Comment by fyang1024** [comment]
yeah, a bit of extra UI is required

**Comment by anjj123** [comment]
Issue referenced here: https://github.com/SpeckleOS/speckle-browser-extension/issues/103
